My Project: main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "kputils.h"
#include "banned.h"
Data Structures
struct node_t
struct list_t
Functions
struct list_t * create_list (void)
Function to create a new double linked list.
void push_head (struct list_t *list, void *data)
void push_tail (struct list_t *list, void *data)
void * pop_head (struct list_t *list)
void * pop_tail (struct list_t *list)
void delete_list (struct list_t *list)
void empty_list (struct list_t *list)
void * get_by_id (struct list_t *list, int id)
void * remove_by_id (struct list_t *list, int id)
int main ()
Variables
static int node_id = 0
Data Structure Documentation
node_t
struct node_t
struct node_t
Definition at line 12 of file main.c.
Data Fields
void * data
int id
struct node_t * next
struct node_t * prev
list_t
struct list_t
Definition at line 19 of file main.c.
Data Fields
struct node_t * head
int size
struct node_t * tail
Function Documentation
create_list()
struct list_t * create_list (void)
Function to create a new double linked list.
Function definition:
List is created empty with NULL links to head and tail. The size counter is set to zero.
Note
Optionally add a note too.
Parameters
[in] void
Returns
List pointer
type struct *list_t
Some text
Definition at line 81 of file main.c.
References list_t::head, list_t::size, and list_t::tail.
Referenced by main().
delete_list()
void delete_list (struct list_t * list)
Definition at line 226 of file main.c.
References list_t::head, and node_t::next.
Referenced by main().
empty_list()
void empty_list (struct list_t * list)
Definition at line 238 of file main.c.
References list_t::head, node_t::next, list_t::size, and list_t::tail.
get_by_id()
void * get_by_id (struct list_t * list, int id)
Definition at line 212 of file main.c.
References node_t::data, list_t::head, node_t::id, and list_t::size.
main()
int main ()
Definition at line 37 of file main.c.
References create_list(), node_t::data, delete_list(), list_t::head, node_t::id, node_t::next, node_t::prev, push_head(), push_tail(), remove_by_id(), list_t::size, and list_t::tail.
pop_head()
void * pop_head (struct list_t * list)
Definition at line 134 of file main.c.
References node_t::data, list_t::head, node_t::next, node_t::prev, list_t::size, and list_t::tail.
pop_tail()
void * pop_tail (struct list_t * list)
Definition at line 155 of file main.c.
References node_t::data, list_t::head, node_t::next, node_t::prev, list_t::size, and list_t::tail.
push_head()
void push_head (struct list_t * list, void * data)
Definition at line 94 of file main.c.
References node_t::data, list_t::head, node_t::id, node_t::next, node_id, node_t::prev, list_t::size, and list_t::tail.
Referenced by main().
push_tail()
void push_tail (struct list_t * list, void * data)
Definition at line 114 of file main.c.
References node_t::data, list_t::head, node_t::id, node_t::next, node_id, node_t::prev, list_t::size, and list_t::tail.
Referenced by main().
remove_by_id()
void * remove_by_id (struct list_t * list, int id)
Definition at line 176 of file main.c.
References node_t::data, list_t::head, node_t::id, node_t::next, node_t::prev, list_t::size, and list_t::tail.
Referenced by main().
Variable Documentation
node_id
int node_id = 0 static
Definition at line 25 of file main.c.
Referenced by push_head(), and push_tail().